apiVersion: v1
kind: PersistentVolumeClaim # 어플리케이션이 사용할 스토리지 요청
metadata:
  name: micro-magentic-one-pvc
  namespace: micro-magentic-one
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rwx-storage