apiVersion: v1
kind: ConfigMap # 어플리케이션 설정 파일 저장
metadata:
  name: micro-magentic-one-config
  namespace: micro-magentic-one
data:
  # === Agent URLs === 
  ORCHESTRATOR_URL: "http://orchestrator.micro-magentic-one.svc.cluster.local:8080"
  CODER_URL: "http://coder.micro-magentic-one.svc.cluster.local:8080"                # Cluster IP DNS (고정 IP에 의존 X)
  FILESURFER_URL: "http://filesurfer.micro-magentic-one.svc.cluster.local:8080"
  WEBSURFER_URL: "http://websurfer.micro-magentic-one.svc.cluster.local:8080"
  COMPUTERTERMINAL_URL: "http://user.micro-magentic-one.svc.cluster.local:8080"
  
  # === Agent Descriptions ===
  WEBSURFER_DESCRIPTION: "A helpful assistant with access to a web browser. Ask them to perform web searches, open pages, and interact with content (e.g., clicking links, scrolling the viewport, filling in form fields, etc.). It can also summarize the entire page, or answer questions based on the content of the page. It can also be asked to sleep and wait for pages to load, in cases where the page seems not yet fully loaded."
  FILESURFER_DESCRIPTION: "An agent that can handle local files."
  CODER_DESCRIPTION: "A helpful and general-purpose AI assistant that has strong language skills, Python skills, and Linux command line skills."
  COMPUTERTERMINAL_DESCRIPTION: "An agent that can execute codes."

  # === User-side ===
  REQUEST_TIMEOUT: "720"        # seconds
  HEALTH_PATH: "/health"
  AGENT_PORT: "8080"
  AGENTS: "coder,filesurfer,websurfer,orchestrator,computerterminal"
  EXECUTER_WORKDIR: "/workspace"
  WEBSURFER_DOWNLOAD_DIR: "/downloads"
  FILESURFER_ROOT: "/data"
  CLEANUP_TEMP_FILES: "false"
  RETRIES: "3"
  MAX_STEPS: "8" # for orchestrator
  APPEND_PREVIOUS: "true"

  # === LLM Settings ===
  MODEL_PROVIDER: "ollama"

  # === GPU Settings ===
  NVIDIA_VISIBLE_DEVICES: "all"  # Use all available GPUs
  NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
  
  # === Ollama Settings ===
  OLLAMA_PREFETCH_MODELS: "llama3.2:1b"
  OLLAMA_MODEL: "llama3.2:1b"
  OLLAMA_HOST: "http://0.0.0.0:11434"
  OLLAMA_KEEP_ALIVE: "5m"
  OLLAMA_NUM_PARALLEL: "1"

  # === Shared Storage ===
  SHARED_STORAGE_PATH: "/data"

  # === Authorization ===
  AUTH_TOKEN: "your_authorization_token"

  