apiVersion: v1
kind: ConfigMap # 어플리케이션 설정 파일 저장
metadata:
  name: micro-magentic-one-orch-config
  namespace: micro-magentic-one
data:
  CODER_URL: "http://coder.micro-magentic-one.svc.cluster.local:8080"                # Cluster IP DNS (고정 IP에 의존 X)
  FILESURFER_URL: "http://filesurfer.micro-magentic-one.svc.cluster.local:8080"
  WEBSURFER_URL: "http://websurfer.micro-magentic-one.svc.cluster.local:8080"
  COMPUTERTERMINAL_URL: "http://user.micro-magentic-one.svc.cluster.local:8080"
  